### ISSUE TITLE
Greta: poweroff command not sent 

### ISSUE THREAD

**Issue by bzizou** [oar-team/oar3#53]
Sometimes (often), poweroff command is not sent by Greta.

It may be related to another error that seems to occur when Greta asks for a node to be Absent:

```
[   DEBUG] [2024-06-12 12:46:00,138] [oar.modules.greta::run:492]: Greta module puts node 'dahu97' in energy saving mode (state: Absent/StandBy)
[...]
[   DEBUG] [2024-06-12 12:46:11,578] [oar.modules.almighty::launch_command:112]: Launching command : [/usr/lib/oar/oar-node-change-state]
[ WARNING] [2024-06-12 12:46:13,235] [oar.modules.node_change_state::run:384]: state change requested for dahu97: {39: 'Absent', 31: 'Absent', 17: 'Absent', 42: 'Absent', 20: 'Absent', 30: 'Absent', 22: 'Absent', 46: 'Absent', 28: 'Absent', 19: 'Absent', 15: 'Absent', 26: 'Absent', 33: 'Absent', 35: 'Absent', 25: 'Absent', 45: 'Absent', 23: 'Absent', 37: 'Absent', 36: 'Absent', 38: 'Absent', 32: 'Absent', 21: 'Absent', 16: 'Absent', 27: 'Absent', 43: 'Absent', 40: 'Absent', 34: 'Absent', 29: 'Absent', 18: 'Absent', 41: 'Absent', 24: 'Absent', 44: 'Absent'}
[ WARNING] [2024-06-12 12:46:13,236] [oar.modules.node_change_state::run:384]: state change requested for dahu98: {49: 'Absent', 68: 'Absent', 75: 'Absent', 73: 'Absent', 72: 'Absent', 51: 'Absent', 65: 'Absent', 70: 'Absent', 59: 'Absent', 58: 'Absent', 66: 'Absent', 77: 'Absent', 57: 'Absent', 47: 'Absent', 67: 'Absent', 54: 'Absent', 55: 'Absent', 76: 'Absent', 71: 'Absent', 56: 'Absent', 48: 'Absent', 50: 'Absent', 61: 'Absent', 60: 'Absent', 69: 'Absent', 52: 'Absent', 53: 'Absent', 78: 'Absent', 64: 'Absent', 62: 'Absent', 74: 'Absent', 63: 'Absent'}
[   DEBUG] [2024-06-12 12:46:13,366] [oar.modules.almighty::launch_command:118]: /usr/lib/oar/oar-node-change-state terminated
[   DEBUG] [2024-06-12 12:46:13,367] [oar.modules.almighty::launch_command:119]: Exit value : 1
[   DEBUG] [2024-06-12 12:46:13,367] [oar.modules.almighty::launch_command:122]: Command failed with error: [ WARNING] [2024-06-12 12:46:13,235] [oar.modules.node_change_state::run:384]: state change requested for dahu97: {39: 'Absent', 31: 'Absent', 17: '
Absent', 42: 'Absent', 20: 'Absent', 30: 'Absent', 22: 'Absent', 46: 'Absent', 28: 'Absent', 19: 'Absent', 15: 'Absent', 26: 'Absent', 33: 'Absent', 35: 'Absent', 25: 'Absent', 45: 'Absent', 23: 'Absent', 37: 'Absent', 36: 'Absent', 38: 'Absent', 32: 'Abse
nt', 21: 'Absent', 16: 'Absent', 27: 'Absent', 43: 'Absent', 40: 'Absent', 34: 'Absent', 29: 'Absent', 18: 'Absent', 41: 'Absent', 24: 'Absent', 44: 'Absent'}
[ WARNING] [2024-06-12 12:46:13,236] [oar.modules.node_change_state::run:384]: state change requested for dahu98: {49: 'Absent', 68: 'Absent', 75: 'Absent', 73: 'Absent', 72: 'Absent', 51: 'Absent', 65: 'Absent', 70: 'Absent', 59: 'Absent', 58: 'Absent', 6
6: 'Absent', 77: 'Absent', 57: 'Absent', 47: 'Absent', 67: 'Absent', 54: 'Absent', 55: 'Absent', 76: 'Absent', 71: 'Absent', 56: 'Absent', 48: 'Absent', 50: 'Absent', 61: 'Absent', 60: 'Absent', 69: 'Absent', 52: 'Absent', 53: 'Absent', 78: 'Absent', 64: '
Absent', 62: 'Absent', 74: 'Absent', 63: 'Absent'}
```

After this error, the poweroff command is not sent

**Comment by bzizou** [comment]
I think that this happens when the node is already in the Absent state, then I suppose that `/usr/lib/oar/oar-node-change-state` returns 1, and then Greta does not continue

**Comment by bzizou** [comment]
Additionnaly, Greta dies often without notice after "Got request: HALT for nodes:" and when there's no node to halt ("Not halting.. because..")

**Comment by bzizou** [comment]
Thanks to this commit e48de7c , we now get the reasons of the Greta errors:

```
[   DEBUG] [2024-06-13 14:49:01,015] [oar.modules.greta::main:678]: Unexpected err=KeyError('dahu98'), type(err)=<class 'KeyError'>; Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/oar/modules/greta.py", line 676, in main
    status=greta.run()
           ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/oar/modules/greta.py", line 512, in run
    del nodes_list_to_process[node]
        ~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'dahu98'
```

**Comment by bzizou** [comment]
fixed by commit 098831
