### ISSUE TITLE
Installation not working properly on both 3.0.0.dev4 and 3.0.0.dev5

### ISSUE THREAD

**Issue by nikosT** [oar-team/oar3#6]
After running the commands according to instructions [Test Alpha Version](http://oar.imag.fr/oar_3/)

And after running the command: `oarsub -I`

I receive the error:
```bash
Traceback (most recent call last):
  File "/usr/local/lib/oar/.oarsub", line 5, in <module>
    from oar.cli.oarsub import cli
  File "/usr/local/lib/python3.7/dist-packages/oar/cli/oarsub.py", line 15, in <module>
    from oar.lib import (config, db, Job)
  File "/usr/local/lib/python3.7/dist-packages/oar/lib/__init__.py", line 58, in __getattr__
    module = __import__(object_origins[name], None, None, [name])
  File "/usr/local/lib/python3.7/dist-packages/oar/lib/models.py", line 4, in <module>
    from sqlalchemy.ext.declarative.api import DeclarativeMeta
ModuleNotFoundError: No module named 'sqlalchemy.ext.declarative.api'
```

Perhaps you should provide a full environment e.g. `pip freeze --all`

**Comment by nikosT** [comment]
I also tried the latest branch (dev5). But I get the below error message in the installation procedure (before accessing the frontend node):

```bash
 oardocker install ./oar3
Installing 'OAR' from /home/nikos/Dropbox/MHX_HY/phd/soar/oar3/oar3
    node | /tmp/install_oar.U4reVkRq/src /
    node | /
    node | Processing /tmp/install_oar.U4reVkRq/src
    node |   Installing build dependencies: started
    node |   Installing build dependencies: finished with status 'done'
    node |   Getting requirements to build wheel: started
    node |   Getting requirements to build wheel: finished with status 'done'
    node |   Preparing metadata (pyproject.toml): started
    node |   Preparing metadata (pyproject.toml): finished with status 'done'
    node | Collecting escapism<2.0.0,>=1.0.1
    node |   Downloading escapism-1.0.1-py2.py3-none-any.whl (3.4 kB)
    node | Collecting fastapi>0.68.0
    node |   Downloading fastapi-0.75.0-py3-none-any.whl (54 kB)
    node | Collecting alembic>1.7.0
    node |   Downloading alembic-1.7.6-py3-none-any.whl (210 kB)
    node | Collecting passlib<2.0.0,>=1.7.4
    node |   Downloading passlib-1.7.4-py2.py3-none-any.whl (525 kB)
    node | Collecting uvicorn<0.15.0,>=0.14.0
    node |   Downloading uvicorn-0.14.0-py3-none-any.whl (50 kB)
    node | Requirement already satisfied: Flask>2.0.0 in /usr/local/lib/python3.7/dist-packages (from oar==3.0.0.dev4) (2.0.2)
    node | Collecting procset<2.0,>=1.0
    node |   Downloading procset-1.0-py3-none-any.whl (12 kB)
    node | Collecting simplejson<4.0.0,>=3.17.2
    node |   Downloading simplejson-3.17.6-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (130 kB)
    node | Collecting psutil<6.0.0,>=5.8.0
    node |   Downloading psutil-5.9.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
    node | Collecting SQLAlchemy-Utils<0.38.0,>=0.37.3
    node |   Downloading SQLAlchemy_Utils-0.37.9-py3-none-any.whl (100 kB)
    node | Requirement already satisfied: toml>0.10.0 in /usr/local/lib/python3.7/dist-packages (from oar==3.0.0.dev4) (0.10.2)
    node | Collecting PyYAML>=5.0
    node |   Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
    node | Requirement already satisfied: Click>=8.0.0 in /usr/local/lib/python3.7/dist-packages (from oar==3.0.0.dev4) (8.0.3)
    node | Requirement already satisfied: ptpython<4.0.0,>=3.0.20 in /usr/local/lib/python3.7/dist-packages (from oar==3.0.0.dev4) (3.0.20)
    node | Collecting pyzmq<23.0.0,>=22.0.3
    node |   Downloading pyzmq-22.3.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.1 MB)
    node | Requirement already satisfied: requests>=2.24.0 in /usr/local/lib/python3.7/dist-packages (from oar==3.0.0.dev4) (2.27.1)
    node | Collecting tabulate<0.9.0,>=0.8.9
    node |   Downloading tabulate-0.8.9-py3-none-any.whl (25 kB)
    node | Collecting psycopg2<3.0.0,>=2.8.6
    node |   Downloading psycopg2-2.9.3.tar.gz (380 kB)
    node |   Preparing metadata (setup.py): started
    node |   Preparing metadata (setup.py): finished with status 'error'
    node |   Downloading psycopg2-2.9.2.tar.gz (380 kB)
    node |   Preparing metadata (setup.py): started
    node |   Preparing metadata (setup.py): finished with status 'error'
    node |   Downloading psycopg2-2.9.1.tar.gz (379 kB)
    node |   Preparing metadata (setup.py): started
    node |   Preparing metadata (setup.py): finished with status 'error'
    node |   Downloading psycopg2-2.9.tar.gz (379 kB)
    node |   Preparing metadata (setup.py): started
    node |   Preparing metadata (setup.py): finished with status 'error'
    node |   Downloading psycopg2-2.8.6.tar.gz (383 kB)
    node |   Preparing metadata (setup.py): started
    node |   Preparing metadata (setup.py): finished with status 'error'
Exception in thread background thread for pid 4281:
Traceback (most recent call last):
  File "/home/nikos/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/nikos/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nikos/anaconda3/lib/python3.9/site-packages/sh.py", line 1683, in wrap
    fn(*rgs, **kwargs)
  File "/home/nikos/anaconda3/lib/python3.9/site-packages/sh.py", line 2662, in background_thread
    handle_exit_code(exit_code)
  File "/home/nikos/anaconda3/lib/python3.9/site-packages/sh.py", line 2349, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/nikos/anaconda3/lib/python3.9/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/bash -c '/usr/bin/docker run -a STDOUT -a STDERR --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined --name oardocker_1647101283.5303345 -v /home/nikos/Dropbox/MHX_HY/phd/soar/oar3/oar3:/tmp/postintall/oar-git:ro oardocker/buster-node:base /root/install_oar.sh /tmp/postintall/oar-git'

  STDOUT:
/tmp/install_oar.U4reVkRq/src /
/
Processing /tmp/install_oar.U4reVkRq/src
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting escapism<2.0.0,>=1.0.1
  Downloading escapism-1.0.1-py2.py3-none-any.whl (3.4 kB)
Collecting fastapi>0.68.0
  Downloading fastapi-0.75.0-py3-none-any.whl (54 kB)
Collecting alembic>1.7.0
  Downloading alembic-1.7.6-py3-none-any.whl (210 kB)
Collecting passlib<2.0.0,>=1.7.4
  Downloading passlib-1.7.4-py2.py3-none-any.whl (525 kB)
Co... (2357 more, please see e.stdout)

  STDERR:
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8qb5d025/psycopg2_eccd187a320b4df7a85e61b84d37e69b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8qb5d025/psycopg2_eccd187a320b4df7a85e61b84d37e69b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ssq6djjh
       cwd: /tmp/pip-install-8qb5d025/psycopg2_eccd187a320b4df7a85e61b84d37e69b/
  Complete output (4 lines):
  runnin... (9758 more, please see e.stderr)

Error: 

  RAN: /usr/bin/bash -c '/usr/bin/docker run -a STDOUT -a STDERR --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined --name oardocker_1647101283.5303345 -v /home/nikos/Dropbox/MHX_HY/phd/soar/oar3/oar3:/tmp/postintall/oar-git:ro oardocker/buster-node:base /root/install_oar.sh /tmp/postintall/oar-git'

  STDOUT:
/tmp/install_oar.U4reVkRq/src /
/
Processing /tmp/install_oar.U4reVkRq/src
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting escapism<2.0.0,>=1.0.1
  Downloading escapism-1.0.1-py2.py3-none-any.whl (3.4 kB)
Collecting fastapi>0.68.0
  Downloading fastapi-0.75.0-py3-none-any.whl (54 kB)
Collecting alembic>1.7.0
  Downloading alembic-1.7.6-py3-none-any.whl (210 kB)
Collecting passlib<2.0.0,>=1.7.4
  Downloading passlib-1.7.4-py2.py3-none-any.whl (525 kB)
Co... (2357 more, please see e.stdout)

  STDERR:
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8qb5d025/psycopg2_eccd187a320b4df7a85e61b84d37e69b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8qb5d025/psycopg2_eccd187a320b4df7a85e61b84d37e69b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ssq6djjh
       cwd: /tmp/pip-install-8qb5d025/psycopg2_eccd187a320b4df7a85e61b84d37e69b/
  Complete output (4 lines):
  runnin... (9758 more, please see e.stderr)

```

**Comment by nikosT** [comment]
I observe that oar-docker with version 3.0.0.dev4 can run oar with 3.0.0.dev4, but not dev5. oar-docker version 3.0.0.dev3 can not run any of the dev4 and dev5 oar versions.

**Comment by nikosT** [comment]
I bypassed the error by running at frontend docker:
`sudo pip install SQLAlchemy==1.3.24`

then I got:
```bash
docker@frontend ~
$ oarsub -I
# INFO:  Moldable instance:  1  Estimated nb resources:  0  Walltime:  3600
#ERROR: unamed error
(-5, 'There are not enough resources for your request')
```

**Comment by adfaure** [comment]
I think that upgrading SQLAlchemy must be done on every node of the docker cluster.

In oar-docker-compose, you can set the debian version to bookworm (bookworm has version 1.4 of sqlalchemy). In this [dockerfile](https://github.com/oar-team/oar-docker-compose/blob/master/dev/Dockerfile#L1). Then rebuild the docker with `oar-docker-compose build`.

**Comment by nikosT** [comment]
Hi @adfaure 
I also had not to add `*` next to `netcat` because in bookworm version, it could not recognize it (while now it installs both versions traditional and bsd). 

However, after successful build and run of the containers, I run the command `docker exec -u user1 -ti dev_frontend_1 bash`. Then from container's terminal, I run:
```bash
user1@frontend:/$ oarsub -I
bash: oarsub: command not found
```

**Comment by adfaure** [comment]
Hello,

Could you check if the service `oardocker-provision.service` exited successfully (`systemctl  status oardocker-provision.service`) on the front end ?

If it didn't could you provide me the output please, with the command `journalctl -u oardocker-provision`.

Thanks

**Comment by nikosT** [comment]
@adfaure thanks again for the help :)
I see no problem now, with oar-docker-compose, where everything is working great:
```
user1@frontend:/$ oarsub --version
OAR version : 3.0.0.dev7
```
With oar-docker, I experience the issue [here](https://github.com/oar-team/oar-docker/issues/62). Until it is solved, I'll work with the oar-docker-compose.

**Comment by nikosT** [comment]
@adfaure, I think is resolved now, and could be closed.
